<<<<<<< HEAD
spring.application.name=SpringBootDcoker

server.port=8090

spring.config.import=azureAppConfiguration
spring.cloud.azure.appconfiguration.stores[0].endpoint=https://appconfigforsprngbootdocker.azconfig.io
spring.cloud.azure.credential.managed-identity-enabled= true
spring.cloud.azure.appconfiguration.stores[0].feature-flags.enabled=true
#spring.cloud.azure.credential.client-id= <client_id>
=======
spring.application.name=SpringBootDocker
server.port=8080
>>>>>>> 2d8afca (Initial Spring Boot Docker setup)
